### ISSUE TITLE
setServiceProperties: Leaving out AllowedHeaders or ExposedHeaders leads to invalid XML

### ISSUE THREAD

**Issue by letmaik** [Azure/azure-storage-node#180]
With BlobService.setServiceProperties, if the `Cors.CorsRule[..].AllowedHeaders` or `ExposedHeaders` is left out, then the library sends an illformed XML document to the API. Those two properties have to be explicitly set to `AllowedHeaders: []`. I think this should be more graceful if you leave out properties, such that it uses defaults or at least outputs a better error instead of sending an invalid XML to the storage API.

```
StorageError: XML specified is not syntactically valid.
...
    at Function.StorageServiceClient._normalizeError (D:\home\site\wwwroot\node_modules\azure-storage\lib\common\services\storageserviceclient.js:1108:23)
    at BlobService.StorageServiceClient._processResponse (D:\home\site\wwwroot\node_modules\azure-storage\lib\common\services\storageserviceclient.js:691:50)
    at Request.processResponseCallback [as _callback] (D:\home\site\wwwroot\node_modules\azure-storage\lib\common\services\storageserviceclient.js:294:37)
    at Request.self.callback (D:\home\site\wwwroot\node_modules\request\request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1044:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:965:12)
```

**Comment by hasonmsft** [comment]
@letmaik , thanks for raising this issue. We'll try to improve it in upcoming release and get you updated when it's ready.

**Comment by hasonmsft** [comment]
@letmaik , the latest version (1.3.0) allow you not setting the `AllowedHeaders` and `ExposedHeaders`.

**Comment by letmaik** [comment]
Great, thanks!
