### ISSUE TITLE
createReadStream throws within the callback for a nonexistant resource

### ISSUE THREAD

**Issue by geoffpatehutch** [Azure/azure-storage-node#204]
myBlobService.createReadStream("containernamethatdoesntexist", myBlob, function (error, result) {

});

or

myBlobService.createReadStream(containerName, "some/blob/that/does/not/exist", function (error, result) {

});

StorageError: NotFound
    at Function.StorageServiceClient._normalizeError (/Users/geoffpate/GitHub/HutchMaster/CCCG/node_modules/azure-storage/lib/common/services/storageserviceclient.js:1146:23)
    at BlobService.StorageServiceClient._processResponse (/Users/geoffpate/GitHub/HutchMaster/CCCG/node_modules/azure-storage/lib/common/services/storageserviceclient.js:706:50)
    at Request.StorageServiceClient._performRequest.self._buildRequestOptions.processResponseCallback [as _callback] (/Users/geoffpate/GitHub/HutchMaster/CCCG/node_modules/azure-storage/lib/common/services/storageserviceclient.js:306:37)
    at Request.init.self.callback (/Users/geoffpate/GitHub/HutchMaster/CCCG/node_modules/azure-storage/node_modules/request/request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)

Error should be returned in the callback

**Comment by geoffpatehutch** [comment]
Sorry, not an issue. Needed to add a .on("error") handler to the returned stream!
