### ISSUE TITLE
'createPageBlobFromStream': throw new RangeError(SR.INVALID_PAGE_END_OFFSET);

### ISSUE THREAD

**Issue by 123wowow123** [Azure/azure-storage-node#212]
The size is specified in multiples of 512 so why am I getting 'Page end offset must be multiple of 512' error? I had issues saving slightly larger sized images so I whipped up this test.

 blobSvc.createPageBlobFromStream(
      'thumb',
      'fileName',
      stream,
      512 \* 1000,  // multiple of 512 for quick test and file is smaller then this size
      {
          contentSettings: {
              contentType: 'image/png'
          }
      }, // options
      function(error, result, response) {
        if (!error) {
          // file uploaded
        } else {
        }
      });

/Users/ianflynn/Code/chronopin_node/node_modules/azure-storage/lib/services/blob/blobservice.js:4895
    throw new RangeError(SR.INVALID_PAGE_END_OFFSET);
    ^

RangeError: Page end offset must be multiple of 512.
    at Object.BlobService._updatePageBlobPagesImpl (/Users/ianflynn/Code/chronopin_node/node_modules/azure-storage/lib/services/blob/blobservice.js:4895:11)
    at Object.BlobService._createPages (/Users/ianflynn/Code/chronopin_node/node_modules/azure-storage/lib/services/blob/blobservice.js:4857:22)
    at RestOperation.run (/Users/ianflynn/Code/chronopin_node/node_modules/azure-storage/lib/common/streams/batchoperation.js:373:12)
    at BatchOperation._runOperation (/Users/ianflynn/Code/chronopin_node/node_modules/azure-storage/lib/common/streams/batchoperation.js:198:15)
    at BatchOperation.addOperation (/Users/ianflynn/Code/chronopin_node/node_modules/azure-storage/lib/common/streams/batchoperation.js:146:8)
    at ChunkStreamWithStream.<anonymous> (/Users/ianflynn/Code/chronopin_node/node_modules/azure-storage/lib/services/blob/blobservice.js:5130:30)
    at emitTwo (events.js:87:13)
    at ChunkStreamWithStream.emit (events.js:172:7)
    at ChunkStreamWithStream.ChunkStream._emitBufferData (/Users/ianflynn/Code/chronopin_node/node_modules/azure-storage/lib/common/streams/chunkstream.js:204:8)
    at ChunkStreamWithStream.ChunkStream._flushInternalBuffer (/Users/ianflynn/Code/chronopin_node/node_modules/azure-storage/lib/common/streams/chunkstream.js:231:10)
    at ChunkStreamWithStream.ChunkStream.end (/Users/ianflynn/Code/chronopin_node/node_modules/azure-storage/lib/common/streams/chunkstream.js:95:8)
    at emitNone (events.js:67:13)
    at MultiStream.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

**Comment by hasonmsft** [comment]
@123wowow123 , for page blob, it requires the file size (stream size for your case) to be multiple of 512 bytes. And for storing media files, block blob is better choice.
