### ISSUE TITLE
Tests error when connection string is not used [OS X]

### ISSUE THREAD

**Issue by peterblazejewicz** [Azure/azure-storage-node#217]
Version 1.3.1

I'm running tests on *nix machine (OS X) and when using option with explicit account and access key env. variables:

``` bash
export AZURE_STORAGE_ACCOUNT="valid storage account name"
export AZURE_STORAGE_ACCESS_KEY="valid storage account key"
```

 the tests seem to fail to run:

``` bash
npm test

> azure-storage@1.3.1 test /Users/piotrblazejewicz/git/azure-storage-node
> jshint lib && nsp check && mocha --no-timeouts --recursive test

(+) No known vulnerabilities found
/Users/piotrblazejewicz/git/azure-storage-node/test/framework/test-suite.js:120
      throw new Error(messages.join(os.EOL));
      ^

Error: This test requires the following environment variables which are not set: AZURE_STORAGE_CONNECTION_STRING
    at TestSuite.validateEnvironment (/Users/piotrblazejewicz/git/azure-storage-node/test/framework/test-suite.js:120:13)
    at new TestSuite (/Users/piotrblazejewicz/git/azure-storage-node/test/framework/test-suite.js:58:8)
    at Object.<anonymous> (/Users/piotrblazejewicz/git/azure-storage-node/test/accountsas-tests.js:56:13)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at /Users/piotrblazejewicz/git/azure-storage-node/node_modules/mocha/lib/mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/piotrblazejewicz/git/azure-storage-node/node_modules/mocha/lib/mocha.js:219:14)
    at Mocha.run (/Users/piotrblazejewicz/git/azure-storage-node/node_modules/mocha/lib/mocha.js:487:10)
    at Object.<anonymous> (/Users/piotrblazejewicz/git/azure-storage-node/node_modules/mocha/bin/_mocha:458:18)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3
npm ERR! Test failed.  See above for more details.
```

To run tests with Azure account I had to use explicit env connection string option.

Thanks!

**Comment by hasonmsft** [comment]
@peterblazejewicz ， thanks for raising this. We'll fix it in upcoming releases. And could you please close 1 of the duplicate issues? :)
