### ISSUE TITLE
unexpected endFlush when uploading a file to Azure.

### ISSUE THREAD

**Issue by hariprasadkulkarni** [Azure/azure-storage-node#250]
I'm using the azure sdk for my Azure operations. One of the use cases is uploading a file to Azure Storage.

I'm using the multipart library to upload the file.

The file name is a param that I'm passing in the multipart request. There is this strange scenario where the upload is failing when the file name is greater than 53 characters in length. 53 might be misleading because I prepend an identifier to the file name before uploading to Azure (this is to create a human readable folder structure).

This is the error stack that I get.

```
Error: unexpected endFlush
    at endFlush (/usr/src/app/server/node_modules/multiparty/index.js:553:22)
    at PassThrough.<anonymous> (/usr/src/app/server/node_modules/multiparty/index.js:632:5)
    at emitNone (events.js:72:20)
    at PassThrough.emit (events.js:166:7)
    at PassThrough.<anonymous> (/usr/src/app/server/node_modules/azure/node_modules/azure-storage/lib/common/util/util.js:401:18)
    at emitOne (events.js:77:13)
    at PassThrough.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at PassThrough.Readable.push (_stream_readable.js:111:10)
    at PassThrough.Transform.push (_stream_transform.js:128:32)
```

This is the point in code where the exception occurs at ```readStream.emit('end');```.

https://github.com/Azure/azure-storage-node/blob/master/lib/common/util/util.js#L401

There is an issue logged on the multiparty library, which describes a similar scenario.

https://github.com/expressjs/node-multiparty/issues/142

**Comment by hasonmsft** [comment]
@hariprasadkulkarni , thanks for reporting this. We'll look into this and get back to you.

**Comment by hariprasadkulkarni** [comment]
@hasonmsft Today I observed this issue while uploading .xlsx files. Nothing to do with the name length. I don't see this with other (popular) file types. Like pdf, png, txt etc.

**Comment by davilin** [comment]
were there any resolution to this? i'm also seeing the issue when trying to upload zip files, but works perfectly fine with jpg/png files.

**Comment by kulkarnih** [comment]
@hasonmsft Any updates on this issue?

**Comment by XiaoningLiu** [comment]
@kulkarnih @davilin Seems you are using multipart library. I even don't know which azure-storage method multipart uses could lead to this error. 

To help us make it more clear. Could you please provide us a simple sample which could stably re-produce this issue? The sample should only depends on azure-storage instead of multipart.

**Comment by kulkarnih** [comment]
@XiaoningLiu This is probably an issue with the multipart library. I have added more comments here.

https://github.com/pillarjs/multiparty/issues/142

**Comment by XiaoningLiu** [comment]
Seems pillarjs/multiparty#142 is resolved and marked as closed. We will close this issue too.
