### ISSUE TITLE
fileService.getFileToStream - 403 Errors

### ISSUE THREAD

**Issue by tombarton** [Azure/azure-storage-node#294]
Apologies for posting this as an issue, but I think this might be an area that needs further development.

I'm using fileService.getFileToStream in a bot-framework application and I'm getting a 403 error:

```{ StorageError: Forbidden
    at Function.StorageServiceClient._normalizeError (/Users/tombarton/Sites/TestApplication/node_modules/azure-storage/lib/common/services/storageserviceclient.js:1174:23)
    at FileService.StorageServiceClient._processResponse (/Users/tombarton/Sites/TestApplication/node_modules/azure-storage/lib/common/services/storageserviceclient.js:729:50)
    at Request.processResponseCallback [as _callback] (/Users/tombarton/Sites/TestApplication/node_modules/azure-storage/lib/common/services/storageserviceclient.js:310:37)
    at Request.self.callback (/Users/tombarton/Sites/TestApplication/node_modules/azure-storage/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/tombarton/Sites/TestApplication/node_modules/azure-storage/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/tombarton/Sites/TestApplication/node_modules/azure-storage/node_modules/request/request.js:965:12)
  name: 'StorageError',
  message: 'Forbidden',
  code: 'Forbidden',
  statusCode: 403,
  requestId: '51ce6605-001a-00c1-1d52-ae966b000000' }
```

My issue is that I can't seem to debug this any further than the error above. When I run my code outside of the bot-framework then it works perfectly so I've ruled out access keys being an issue.

Are there any plans to increase the level of debugging?

**Comment by hasonmsft** [comment]
@tombarton , the logger level is already supported. 

```
var azureStorage = require('azure-storage');
...
fileService.logger.level = azureStorage.Logger.LogLevels.DEBUG;
```
As the authentication is based on HMAC. If your framework injects some HTTP headers after our library calculating the HMAC, you'll get the 403. 

You can try to capture the network trace together with the library's log for troubleshooting.
