### ISSUE TITLE
Requested URI does not represent any resource on the server

### ISSUE THREAD

**Issue by sharathbaddam** [Azure/azure-storage-node#295]
Hello,

I've been using azure-storage version 1.0.0 till now. I tried to upgrade it to newer version (2.1.0), but I'm getting error when i try to send a queue message.

here is the error stack:-

```
test failed in this scenario with following error >> 
{ StorageError: The requested URI does not represent any resource on the server.
RequestId:9cd70461-0003-00b9-3ef6-b24223000000
Time:2017-04-11T19:05:12.1573135Z
    at Function.StorageServiceClient._normalizeError (C:\Users\tester\Desktop\test\cgp-endpoint-azur
e\node_modules\azure-storage\lib\common\services\storageserviceclient.js:1108:23)
    at QueueService.StorageServiceClient._processResponse (C:\Users\tester\Desktop\test\cgp-endpoint
-azure\node_modules\azure-storage\lib\common\services\storageserviceclient.js:691:50)
    at Request.processResponseCallback [as _callback] (C:\Users\tester\Desktop\test\cgp-endpoint-azu
re\node_modules\azure-storage\lib\common\services\storageserviceclient.js:294:37)
    at Request.self.callback (C:\Users\tester\Desktop\test\cgp-endpoint-azure\node_modules\request\r
equest.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\tester\Desktop\test\cgp-endpoint-azure\node_modules\request\req
uest.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\tester\Desktop\test\cgp-endpoint-azure\node_modules\req
uest\request.js:965:12)
  name: 'StorageError',
  message: 'The requested URI does not represent any resource on the server.\nRequestId:9cd70461-000
3-00b9-3ef6-b24223000000\nTime:2017-04-11T19:05:12.1573135Z',
  code: 'InvalidUri',
  uripath: '/sample321/sample321/messages',
  statusCode: 400,
  requestId: '9cd70461-0003-00b9-3ef6-b24223000000' }
```
I tried to revert back to version 1.0.0, it worked without any errors.

Any help is really appreciated.

**Comment by hasonmsft** [comment]
@sharathbaddam , can you share the code to reproduce this issue? Just replace the real key with a fake key.

**Comment by sharathbaddam** [comment]
I used container name twice.
while creating a queue service and while posting messages to queue service.
