### ISSUE TITLE
Error: StorageError: The specified block list is invalid.

### ISSUE THREAD

**Issue by jamesdixon** [Azure/azure-storage-node#304]
Hi, 

I am periodically running into this error when uploading a blob via `createWriteStreamToBlockBlob`. Here's the entire trace:

```
[05/04/2017 20:21:02 > d36cad: ERR ] undefined:1
[05/04/2017 20:21:02 > d36cad: ERR ] (function (f, ctx) { return function (d, cb) { return f(d, cb, ctx); }; })
[05/04/2017 20:21:02 > d36cad: ERR ]                                                       ^
[05/04/2017 20:21:02 > d36cad: ERR ] Error: StorageError: The specified block list is invalid.
[05/04/2017 20:21:02 > d36cad: ERR ] RequestId:4e538660-0001-0069-7b13-c56fda000000
[05/04/2017 20:21:02 > d36cad: ERR ] Time:2017-05-04T20:21:02.5105267Z
[05/04/2017 20:21:02 > d36cad: ERR ]     at Function.StorageServiceClient._normalizeError (D:\home\site\wwwroot\App_Data\jobs\continuous\scripthost\ScheduleBackup\node_modules\azure-storage\lib\common\services\storageserviceclient.js:1174:23)
[05/04/2017 20:21:02 > d36cad: ERR ]     at BlobService.StorageServiceClient._processResponse (D:\home\site\wwwroot\App_Data\jobs\continuous\scripthost\ScheduleBackup\node_modules\azure-storage\lib\common\services\storageserviceclient.js:729:50)
[05/04/2017 20:21:02 > d36cad: ERR ]     at Request.processResponseCallback [as _callback] (D:\home\site\wwwroot\App_Data\jobs\continuous\scripthost\ScheduleBackup\node_modules\azure-storage\lib\common\services\storageserviceclient.js:310:37)
[05/04/2017 20:21:02 > d36cad: ERR ]     at Request.self.callback (D:\home\site\wwwroot\App_Data\jobs\continuous\scripthost\ScheduleBackup\node_modules\request\request.js:187:22)
[05/04/2017 20:21:02 > d36cad: ERR ]     at emitTwo (events.js:106:13)
[05/04/2017 20:21:02 > d36cad: ERR ]     at Request.emit (events.js:191:7)
[05/04/2017 20:21:02 > d36cad: ERR ]     at Request.<anonymous> (D:\home\site\wwwroot\App_Data\jobs\continuous\scripthost\ScheduleBackup\node_modules\request\request.js:1044:10)
[05/04/2017 20:21:02 > d36cad: ERR ]     at emitOne (events.js:96:13)
[05/04/2017 20:21:02 > d36cad: ERR ]     at Request.emit (events.js:188:7)
[05/04/2017 20:21:02 > d36cad: ERR ]     at IncomingMessage.<anonymous> (D:\home\site\wwwroot\App_Data\jobs\continuous\scripthost\ScheduleBackup\node_modules\request\request.js:965:12)
[05/04/2017 20:21:02 > d36cad: ERR ]     at emitNone (events.js:91:20)
[05/04/2017 20:21:02 > d36cad: ERR ]     at IncomingMessage.emit (events.js:185:7)
[05/04/2017 20:21:02 > d36cad: ERR ]     at endReadableNT (_stream_readable.js:974:12)
[05/04/2017 20:21:02 > d36cad: ERR ]     at _combinedTickCallback (internal/process/next_tick.js:74:11)
[05/04/2017 20:21:02 > d36cad: ERR ]     at process._tickCallback (internal/process/next_tick.js:98:9)
[05/04/2017 20:21:02 > d36cad: ERR ]     at Error (native)
[05/04/2017 20:21:02 > d36cad: ERR ]     at Object.handleUncaughtException (<anonymous>:1:55)
[05/04/2017 20:21:02 > d36cad: ERR ]     at process.<anonymous> (D:\home\site\wwwroot\App_Data\jobs\continuous\scripthost\bin\azurefunctions\functions.js:17:17)
[05/04/2017 20:21:02 > d36cad: ERR ]     at emitOne (events.js:101:20)
[05/04/2017 20:21:02 > d36cad: ERR ]     at process.emit (events.js:188:7)
[05/04/2017 20:21:02 > d36cad: ERR ]     at process._fatalException (bootstrap_node.js:296:26)
[05/04/2017 20:21:04 > d36cad: SYS ERR ] Job failed due to exit code 7
```

I haven't been able to find a great explanation as to what it actually means. Can anyone provide some insight?

Here's a snippet from my code:

```js
// create a consistent, but unique id for the file
const hashedID = new HashID('scout').encode(business.id, Moment(business.created_at).unix());

return new Promise((resolve, reject) => {

    const blobName = `${hashedID}.csv`;

    // create the streams
    const readStream = Knex.raw('SELECT * FROM get_schedule_backup(?, ?)', [business.id, internals.daysAhead]);

    const stringifyStream = Stringify({
        header: true,
        formatters: {
            date: (v) => Moment(v).format(DATE_FORMAT)
        }
    });

    const blobWriteStream = blobService.createWriteStreamToBlockBlob(
        internals.blobContainer,
        blobName,
        (error, result, response) => {

            if (!error) {
                resolve(response);
            }
            else {
                reject(err);
            }
        }
    );

    // 1. Get the appointments
    // 2. Convert to CSV format
    // 3. Write to Azure Blob
    readStream
        .pipe(stringifyStream)
        .pipe(blobWriteStream);

    // catch any errors upstream
    readStream.on('error', (err) => reject(err));
    stringifyStream.on('error', (err) => reject(err));
})
```

**UPDATE: I'm running Azure Storage 2.1**

Thanks!

**Comment by jamesdixon** [comment]
I added the following options and it seems to have resolved the issue:

```js
{
                            blockIdPrefix: 'block',
                            contentSettings: {
                                contentType: 'text/csv'
                            }
                        },
```

Does that make sense that would fix it?

**Comment by XiaoningLiu** [comment]
Hi @jamesdixon , the error is returned from server side and it relates to the auto generated blockIds. There are several server-side limitations for the blockId generated in client side. 

https://docs.microsoft.com/en-us/rest/api/storageservices/put-block-list

The option 'blockIdPrefix' overrides the auto generated blockIdPrefix in your workaround. And does the error randomly happen? Can you provide related 400 Http requests and their payloads, so we can have a better understanding of the issue.

**Comment by XiaoningLiu** [comment]
@isualize What's your error message?

**Comment by isualize** [comment]
@XiaoningLiu appearently it was an invalid blob. Probably something happened while writing to it and now im trying to overwrite it and im getting the 400 statuscode as a result.

**Comment by cryptoqween** [comment]
Hey guys, getting this error too while uploading large files.
I am using async parallel to upload files and sometimes the same task has its callback called twice from the blob service:

console log looks like this: 

```
starting Task1
callback from blobSvc.createBlockBlobFromLocalFile Task1
saved file in Task1

//Here it's being called the second time
callback from blobSvc.createBlockBlobFromLocalFile Task1
StorageError: The specified block list is invalid.
RequestId:e734306f-301e-00b1-2e60-153032000000
Time:2019-05-28T14:20:55.2516716Z

Failed for Task1
```

**Comment by XiaoningLiu** [comment]
@cryptoqween SDK shouldn't callback twice, it should be fixed. 

In the mean time, the error `The specified block list is invalid` is most likely caused by wrong uploaded blockID list. Are there 2 uploading session for the same blob?

Also recommend to try with our latest released V10 storage JS SDK:
https://www.npmjs.com/package/@azure/storage-blob
https://github.com/Azure/azure-storage-js/blob/master/blob/samples/highlevel.sample.js

**Comment by himanshubillore** [comment]
Any updates? I am getting same error for upload of large size, say more than 80GB. My Blob Name is properly incremented, so it is not because of uploading to same blob, as others are reporting.
method:PUT, uri:/xxxx/<blobNamePrefix>_1?comp=blocklist

**Comment by balindersingh** [comment]
getting this error randomly .. I am using Azure SDK..
`WebClient myWebClient = new WebClient();
// Open a stream to point to the data stream coming from the Web resource.
Stream myStream = myWebClient.OpenRead(PublicDownloadLink);
string blobFileName = "MyFile_" + DateTime.Now.ToString("yyyyMMddHHmmss") + fileExtension;
using (var reader = new StreamReader(myStream))
{
    if (Microsoft.Azure.Storage.CloudStorageAccount.TryParse(this.MyOptions.WebJobStorageConnection, out Microsoft.Azure.Storage.CloudStorageAccount cloudStorageAccount))
    {
        CloudBlobClient cloudBlobClient = new CloudBlobClient(cloudStorageAccount.BlobEndpoint, cloudStorageAccount.Credentials);
        CloudBlobContainer cloudBlobContainer = cloudBlobClient.GetContainerReference("logcontainer");
        CloudBlockBlob cloudBlockBlob = cloudBlobContainer.GetBlockBlobReference(blobFileName);
        await cloudBlockBlob.UploadFromStreamAsync(reader.BaseStream);
        _log.LogInformation("[UploadLogFileToAzureBlobAsync] Uploaded to Azure");
    }
    else
    {
        _log.LogError("[UploadLogFileToAzureBlobAsync] Failed to upload to Azure");
    }
}`
