### ISSUE TITLE
createWriteStreamToBlockBlob doesn't respond when accessConditions is set

### ISSUE THREAD

**Issue by mariecl** [Azure/azure-storage-node#319]
I am trying to upload an image to my blob storage. My image is ready to be uploaded in the form of a stream. I don't know the length of that stream, so I am using `createWriteStreamToBlockBlob` instead of `createBlockBlobFromStream`.

The below code uploads the image successfully as long as the `accessConditions` property is not set. If I do set `accessConditions`, the blob storage doesn't respond anymore. It doesn't return an error, it doesn't throw an exception, it just stops responding.

Is this a bug or are `accessConditions` not supported by this function? For what it's worth, the [documentation](https://github.com/Azure/azure-storage-node/blob/master/lib/services/blob/blobservice.core.js#L3055) states this function accepts an `accessConditions` options.

```node
const azureStorage = require('azure-storage');
const blobService = azureStorage.createBlobService(accountName, accountKey);
const options = {
  // accessConditions: azureStorage.AccessCondition.generateIfNotExistsCondition(),
  blobType: 'block',
  metadata: { name: 'name' },
  timeoutIntervalInMs: 30000,
};
var file; // it's a stream

file.pipe(blobService.createWriteStreamToBlockBlob('container', 'fileName', options, function onResponse(error, result) {
  if (error) {
    return reject(error);
  }

  return resolve('success');
}));
```

For context, I am trying to use `accessConditions` with the purpose of setting a constraint to not overwrite existing blobs.

I am using azure-storage-node version 2.2.0, node version 8.1.0, and npm version 5.0.3.

**Comment by XiaoningLiu** [comment]
Hi @mariecl 

An unhandled exception when I tried in Node.js 6.11.0. It's strange, will try to test on 8.1.0.

```
events.js:160
      throw er; // Unhandled 'error' event
      ^
StorageError: The specified blob already exists.
RequestId:d330d309-0001-00db-378c-f08264000000
Time:2017-06-29T03:59:05.4114863Z
    at Function.StorageServiceClient._normalizeError (D:\GitHub\XiaoningLiu\nodejs-codes\node_modules\azure-storage\lib\common\services\storageserviceclient.js:1174:23)
    at BlobService.StorageServiceClient._processResponse (D:\GitHub\XiaoningLiu\nodejs-codes\node_modules\azure-storage\lib\common\services\storageserviceclient.js:729:50)
    at Request.processResponseCallback [as _callback] (D:\GitHub\XiaoningLiu\nodejs-codes\node_modules\azure-storage\lib\common\services\storageserviceclient.js:310:37)
    at Request.self.callback (D:\GitHub\XiaoningLiu\nodejs-codes\node_modules\request\request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (D:\GitHub\XiaoningLiu\nodejs-codes\node_modules\request\request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (D:\GitHub\XiaoningLiu\nodejs-codes\node_modules\request\request.js:965:12)
```

**Comment by XiaoningLiu** [comment]
Latest LTS v8.10.0 still doesn't re-produce this issue. An error will returned by designed. I'm going to close this issue due to cannot reproduce, feel free to re-open it if you still have this issue.

```
events.js:183
      throw er; // Unhandled 'error' event
      ^
StorageError: The specified blob already exists.
RequestId:567dd2a1-901e-00ff-293d-bc1b2a000000
Time:2018-03-15T09:09:21.6256316Z
    at Function.StorageServiceClient._normalizeError (D:\github\xiaoningliu\nodejs-codes\node_modules\azure-storage\lib\common\services\storageserviceclient.js:1191:23)
    at BlobService.StorageServiceClient._processResponse (D:\github\xiaoningliu\nodejs-codes\node_modules\azure-storage\lib\common\services\storageserviceclient.js:738:50)
    at Request.processResponseCallback [as _callback] (D:\github\xiaoningliu\nodejs-codes\node_modules\azure-storage\lib\common\services\storageserviceclient.js:311:37)
    at Request.self.callback (D:\github\xiaoningliu\nodejs-codes\node_modules\azure-storage\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (D:\github\xiaoningliu\nodejs-codes\node_modules\azure-storage\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (D:\github\xiaoningliu\nodejs-codes\node_modules\azure-storage\node_modules\request\request.js:1085:12)
```

**Comment by komalpharate** [comment]
Hi,
I'm getting the above mentioned issue.
Anybody solved it?

**Comment by XiaoningLiu** [comment]
@komalpharate What's your Node.js version?

**Comment by komalpharate** [comment]
v6.14.0

**Comment by XiaoningLiu** [comment]
Hi @komalpharate 

`createWriteStreamToBlockBlob` is designed to upload all blocks with PutBlock operation, then finally commit the blocks using PutBlockList.

The reason is [PutBlock ](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block)doesn’t support AccessConditions, only [PutBlockList ](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block-list)supports. So you need to wait all the blocks finish uploading, then get an “Blob already exists” error.

I think your expectation is getting the error at the beginning of the upload. But it cannot.

Recommend to use [lease ](https://docs.microsoft.com/en-us/rest/api/storageservices/lease-blob)to avoid concurrency conflicts.

**Comment by chardmd** [comment]
is there an API available for createWriteStreamToBlockBlob that supports 'lease'?
