### ISSUE TITLE
Unrecognized key "EndpointSuffix" in connection string

### ISSUE THREAD

**Issue by BendingBender** [Azure/azure-storage-node#357]
Hi, I'm trying to use the [az-bunyan](https://github.com/sandorfr/az-bunyan) package that uses this lib to connect to azure storage.

Provided the connection string `DefaultEndpointsProtocol=https;AccountName=some-account;AccountKey=some-key;EndpointSuffix=core.cloudapi.de` I get the following exception from this lib:

```
node_modules/azure-storage/lib/common/services/servicesettings.js:92
      throw new Error(util.format(SR.INVALID_CONNECTION_STRING_BAD_KEY, key));
      ^

Error: Connection string contains unrecognized key: "EndpointSuffix"
    at Object.exports.parseAndValidateKeys (node_modules/azure-storage/lib/common/services/servicesettings.js:92:13)
    at Function.StorageServiceSettings.createFromConnectionString (node_modules/azure-storage/lib/common/services/storageservicesettings.js:106:43)
    at Function.StorageServiceClient.getStorageSettings (node_modules/azure-storage/lib/common/services/storageserviceclient.js:712:53)
    at new TableService (node_modules/azure-storage/lib/services/table/tableservice.js:72:53)
    at Object.exports.createTableService (node_modules/azure-storage/lib/azure-storage.js:62:10)
    at new TableStorageStream (node_modules/az-bunyan/lib/az-bunyan/index.js:37:33)
    at Object.createTableStorageStream (node_modules/az-bunyan/lib/az-bunyan/index.js:110:37)
    at Object.<anonymous> (logger.js:8:30)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
```

I've copy-pasted the connection string directly from my azure account page, so this is definitely this lib that is mis-behaving.

Is there anything I can do to work around this issue?

**Comment by jiacfan** [comment]
Hi, @BendingBender 

[az-bunyan](https://github.com/sandorfr/az-bunyan/blob/master/package.json) is using azure-storage version 0.3.3, and Azure storage node.js client library start to support EndpointSuffix for all service constructors from version 1.2.0 (please note latest version is 2.5.0).

Would you please contact owners of [az-bunyan](https://github.com/sandorfr/az-bunyan/blob/master/package.json) to see if it's possible for them to upgrade the Azure storage client library version. Or would you please try to refer to the latest code, and add the support in your private repo?

Best Regards,
Jiachen

**Comment by BendingBender** [comment]
Thank you for the quick response. I'll submit a pull request there.

**Comment by jiacfan** [comment]
Welcome!

Best Wishes

**Comment by andrzejmartyna** [comment]
Hi, @BendingBender ,
I've also found solution here which worked for me and I can still use azure-storage 0.3.3:
https://github.com/Azure/azure-sdk-for-php/issues/928

It means that you replace this:
;EndpointSuffix=core.cloudapi.de
with this:
;BlobEndpoint=https://some-account.blob.core.cloudapi.de
