### ISSUE TITLE
getBlobToText of public blob calls callback twice

### ISSUE THREAD

**Issue by adgang** [Azure/azure-storage-node#366]
```
  var debug = require('debug')('sample-app');
  var blobService = azure.createBlobService('DefaultEndpointsProtocol=https;AccountName=something;AccountKey=TWFu;EndpointSuffix=core.windows.net');
  var blobPromise = new Promise(function(resolve, reject) {
      blobService.getBlobToText('somecontainer', 'somefile.json',
        (err, blobData, blob) => {
          if (err && err.code === 'BlobNotFound') {
            debug('Blob doesnt exist. Assuming empty json');
            resolve({});
          } else if (err) {
            debug("Couldn't download blob:", 'somefile.json');
            debug(err.code);
            reject(err);
          } else {
            debug("Sucessfully downloaded blob:", 'somefile.json');
            debug('blobData', blobData);
            var config = JSON.parse(blobData);
            resolve(config);
          }
      });
  });
```

prints:
```
 sample-app Couldn't download blob: somefile.json +0ms
 sample-app AuthenticationFailed +1ms
Unhandled rejection Error
    at Function.StorageServiceClient._normalizeError (/***/node_modules/azure-storage/lib/common/services/storageserviceclient.js:1189:23)
    at BlobService.StorageServiceClient._processResponse (/***/node_modules/azure-storage/lib/common/services/storageserviceclient.js:736:50)
    at Request.processResponseCallback [as _callback] (/***/node_modules/azure-storage/lib/common/services/storageserviceclient.js:311:37)
    at Request.self.callback (/***/node_modules/azure-storage/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/***/node_modules/azure-storage/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/***/node_modules/azure-storage/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

  sample-app Sucessfully downloaded blob: somefile.json +0ms
  sample-app blobData { "a": "apple" }
```

**Comment by adgang** [comment]
Looks like I called this piece of code twice in my app. Still doesn't explain why there were two different responses. 

PS: I got my work done using anonymous blob service. You might close the issue unless you want to track the above response.

**Comment by jiacfan** [comment]
Hi, @adgang 

Thanks for contacting us, and reporting issue.

Glad to know your scenario got work. And for two different responses, does the issue get steady repro when you send two requests now? Could you catch the package returned? And could you provide the detailed HTTP package info for two responses? Is there anything like SAS expired? And what's the resolve function do? Does the resolve function influence the blob?

Parallel read works fine in our side. So it would be great if you can provide more info, and we can see if it's a potential issue.

Thanks,
Jiachen

**Comment by vinjiang** [comment]
Feel free to let us know if further assistance needed.
