### ISSUE TITLE
StorageServiceClient._normalizeError

### ISSUE THREAD

**Issue by ferrantejake** [Azure/azure-storage-node#379]
I am working with the Tables services and occasionally, without consistency, I am getting this error.

**Under what circumstances the issue appears**
This error occurs without any obvious cause during the run-time of my application. There is no obvious time interval or series of events that occur which leads up to this - the app can sit idly and it will happen every so often. I don't even need to be actively using the module. One of the first thing my app does when it starts up is create tables but doesn't get further than that before I see this error sometimes.
  
**What is the impact**
Seemingly no side effects

```
uncaught exception Error
    at Function.StorageServiceClient._normalizeError (/home/jakef/Documents/Code/Droplit/droplit.io-services/projects/@droplit/dq/node_modules/azure-storage/lib/common/services/storageserviceclient.js:1045:23)
    at BatchResult._parseOperation (/home/jakef/Documents/Code/Droplit/droplit.io-services/projects/@droplit/dq/node_modules/azure-storage/lib/services/table/models/batchresult.js:214:51)
    at /home/jakef/Documents/Code/Droplit/droplit.io-services/projects/@droplit/dq/node_modules/azure-storage/lib/services/table/models/batchresult.js:162:29
    at Array.forEach (<anonymous>)
    at BatchResult.parse (/home/jakef/Documents/Code/Droplit/droplit.io-services/projects/@droplit/dq/node_modules/azure-storage/lib/services/table/models/batchresult.js:155:18)
    at processResponseCallback (/home/jakef/Documents/Code/Droplit/droplit.io-services/projects/@droplit/dq/node_modules/azure-storage/lib/services/table/tableservice.js:1147:39)
    at Request.processResponseCallback [as _callback] (/home/jakef/Documents/Code/Droplit/droplit.io-services/projects/@droplit/dq/node_modules/azure-storage/lib/common/services/storageserviceclient.js:303:13)
    at Request.self.callback (/home/jakef/Documents/Code/Droplit/droplit.io-services/projects/@droplit/dq/node_modules/azure-storage/node_modules/request/request.js:199:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7) +17m
```

**Comment by XiaoningLiu** [comment]
Hi @ferrantejake, thanks for reporting. It's bit difficult to debug without stable reproducing patterns. It the batch operation right? Does it related with the Table entity data in your table? Does the HTTP request successful?

I'll add more focus on related cases in our future validation and testing. And if you have further findings or logs please post here, let's keep monitor this.

**Comment by vinjiang** [comment]
Feel free to let us know if we can be of any further assistance.
