### ISSUE TITLE
Some tests files due to Uncaught TypeError [ERR_INVALID_ARG_TYPE] 

### ISSUE THREAD

**Issue by peterblazejewicz** [Azure/azure-storage-node#396]
I'm running tests on OSX using current dev branch and the 3 of all tests fail due to issue that could be exactly the same problem somewhere in the stack, which looks like something related to streams. Could it be that newer Node version (here 8.9/9.3) uses updated stream impl compared to original one?

Thanks!

```sh
  1) blob-uploaddownload-tests
       blob-rangedownload-tests
         getPageRanges:
     Uncaught TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function
      at WriteStream.close (fs.js:2298:10)
      at WriteStream.<anonymous> (lib/services/blob/blobservice.core.js:5446:23)
      at finishMaybe (_stream_writable.js:616:14)
      at afterWrite (_stream_writable.js:467:3)
      at onwrite (_stream_writable.js:457:7)
      at fs.js:2287:5
      at FSReqWrap.wrapper [as oncomplete] (fs.js:2253:5)

  2) blob-uploaddownload-tests
       getBlockBlobToFile
         should download a block blob to a local file in chunks:
     Uncaught TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function
      at WriteStream.close (fs.js:2298:10)
      at WriteStream.<anonymous> (lib/services/blob/blobservice.core.js:5446:23)
      at finishMaybe (_stream_writable.js:616:14)
      at afterWrite (_stream_writable.js:467:3)
      at onwrite (_stream_writable.js:457:7)
      at fs.write (fs.js:2242:5)
      at FSReqWrap.wrapper [as oncomplete] (fs.js:703:5)

  3) FileUploadDownload
       getFileToLocalFile
         should download a file to a local file in chunks:
     Uncaught TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function
      at WriteStream.close (fs.js:2298:10)
      at WriteStream.<anonymous> (lib/services/file/fileservice.core.js:3609:23)
      at finishMaybe (_stream_writable.js:616:14)
      at afterWrite (_stream_writable.js:467:3)
      at onwrite (_stream_writable.js:457:7)
      at fs.write (fs.js:2242:5)
      at FSReqWrap.wrapper [as oncomplete] (fs.js:703:5)
```

**Comment by BggClr** [comment]
This is not only the tests. The issue is related with breaking change for fs API in node 9.3.0 - you can find more in this comment https://stackoverflow.com/a/48037900 which requires a function to be provided to the onclose events. Seems like it requires quite lot code changes from MS to this repo to fix this issue

**Comment by XiaoningLiu** [comment]
Hi @peterblazejewicz @BggClr , the fix has already sent as a commit https://github.com/Azure/azure-storage-node/pull/392/commits/19dfe74b3db45ed6c225eb1dd7aa5731edead044 in PR https://github.com/Azure/azure-storage-node/pull/392. As a part of next release.

**Comment by BggClr** [comment]
@XiaoningLiu will it be 2.8.0?

**Comment by XiaoningLiu** [comment]
Yes : )
