### ISSUE TITLE
createBlockBlobFromLocalFile confusing behavior

### ISSUE THREAD

**Issue by xals99** [Azure/azure-storage-node#398]
When my file is small enough to fit in one block I get BlobResult object. When my file is bigger than block size I get object with property 'commmittedBlocks'. In documentation I don't see anything about that i should commit blocks manually like createBlockFromText? Maybe I misunderstand something. I use Azurite emulator on linux. azure-storage (2.7.0), azurite (1.8.4).

When I try retrieve small file with getBlobToStream everything is ok. When I try with big file I get error

> /home/mat/server/node_modules/azure-storage/lib/services/blob/models/blocklistresult.js:64
  if (blockListXml.CommittedBlocks && blockListXml.CommittedBlocks.Block) {
                   ^
TypeError: Cannot read property 'CommittedBlocks' of undefined

**Comment by XiaoningLiu** [comment]
Hi @xals99,

`createBlockBlobFromLocalFile` is a method for uploading. When the local file size is larger than a default value, Node.js client library will split the file into different blocks, and uploads each block via different HTTP PUT requests, after all the blocks uploads successfully, a PUT BLOCK LIST HTTP request will be performed.

Does your error occur when calling `createBlockBlobFromLocalFile`?

**Comment by xals99** [comment]
I upload file (~40MB) calling `createBlockBlobFromLocalFile`. Error occured when calling `getBlobToStream`.

/home/mat/server/node_modules/azure-storage/lib/services/blob/models/blocklistresult.js:64
  if (blockListXml.CommittedBlocks && blockListXml.CommittedBlocks.Block) {
                   ^

TypeError: Cannot read property 'CommittedBlocks' of undefined
    at Object.exports.parse (/home/mat/server/node_modules/azure-storage/lib/services/blob/models/blocklistresult.js:64:20)
    at processResponseCallback (/home/mat/server/node_modules/azure-storage/lib/services/blob/blobservice.core.js:3468:56)
    at Request.processResponseCallback [as _callback] (/home/mat/server/node_modules/azure-storage/lib/common/services/storageserviceclient.js:321:13)
    at Request.self.callback (/home/mat/server/node_modules/request/request.js:188:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/mat/server/node_modules/request/request.js:1171:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/mat/server/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)`
`

**Comment by XiaoningLiu** [comment]
Not understand. `getBlobToStream` is used for downloading, but the `createBlockBlobFromLocalFile` is for uploading. Please show some sample code describing this issue.

**Comment by xals99** [comment]
I upload file like that:
```
blobService.createBlockBlobFromLocalFile(CONTAINER, blobName, filePath, function (error, result, response) {
    if (error) {
      cb(error);
    } else {
      log(result.name, 'file uploaded on Azure Storage');
      cb();
    }
  });
```

I try to download file
```
blobService.getBlobToStream(CONTAINER, blobName, fs.createWriteStream(blobName), (error, result, response) => {
    if (error) {
      console.error(error);
    } else {
      log('Downloaded file:', blobName);
    }
  });
```
But I get error
```
/home/mat/server/node_modules/azure-storage/lib/services/blob/models/blocklistresult.js:64
  if (blockListXml.CommittedBlocks && blockListXml.CommittedBlocks.Block) {
                   ^

TypeError: Cannot read property 'CommittedBlocks' of undefined
    at Object.exports.parse (/home/mat/server/node_modules/azure-storage/lib/services/blob/models/blocklistresult.js:64:20)
    at processResponseCallback (/home/mat/server/node_modules/azure-storage/lib/services/blob/blobservice.core.js:3468:56)
    at Request.processResponseCallback [as _callback] (/home/mat/server/node_modules/azure-storage/lib/common/services/storageserviceclient.js:321:13)
    at Request.self.callback (/home/mat/server/node_modules/request/request.js:188:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/mat/server/node_modules/request/request.js:1171:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/mat/server/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by xals99** [comment]
I tested on real Azure Storage and it works. There is probably a bug in the Azurite package.

**Comment by XiaoningLiu** [comment]
Good to know that!
