### ISSUE TITLE
Exception in Validator 

### ISSUE THREAD

**Issue by 3jr** [Azure/azure-storage-node#400]
I encountered the following error:
```
TypeError: This library (validator.js) validates strings only
    at assertString (%SOURCE%\node_modules\validator\lib\util\assertString.js:9:11)
    at Object.isInt (%SOURCE%\node_modules\validator\lib\isInt.js:18:30)
    at FileReadStream.destroy (%SOURCE%\node_modules\azure-storage\lib\common\streams\filereadstream.js:247:18)
    at streamCallback (%SOURCE%\node_modules\azure-storage\lib\services\blob\blobservice.node.js:377:18)
    at finalCallback (%SOURCE%\node_modules\azure-storage\lib\services\blob\blobservice.core.js:4488:7)
    at %SOURCE%\node_modules\azure-storage\lib\common\services\storageserviceclient.js:1000:11
    at processResponseCallback (%SOURCE%\node_modules\azure-storage\lib\services\blob\blobservice.core.js:4491:5)
    at Request.processResponseCallback [as _callback] (%SOURCE%\node_modules\azure-storage\lib\common\services\storageserviceclient.js:321:13)
    at Request.self.callback (%SOURCE%\node_modules\request\request.js:188:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (%SOURCE%\node_modules\request\request.js:1171:10)
    at Request.emit (events.js:159:13)
```

and I could imagine this to be a bug.

I found https://github.com/Azure/azure-storage-node/blob/d789db2de5185b28486638d2513e4ef2b07ecf1f/lib/common/streams/filereadstream.js#L247 and it has the following code:
``` javascript

  // when the stream is closed immediately after creating it
  if (!validator.isInt(this._fd)) {
    this.once('open', close);
    return;
  }
```

A possible fix is this:
``` javascript
  // when the stream is closed immediately after creating it
  if (!validator.isInt(this._fd + '')) {
    this.once('open', close);
    return;
  }
```

https://www.npmjs.com/package/validator explicitly states that it only validates strings and recommends `+ ''` approach and https://nodejs.org/api/fs.html#fs_fs_open_path_flags_mode_callback explicitly calls out the type to be an integer. So `this._fd` is ether an integer of `null` (as initialized).  I could imagine that the use of validator is not ideal in this context (as it's only for strings). Maybe explicitly compare with `null` or something.

**Comment by XiaoningLiu** [comment]
@3jr Thanks! We definitely should follow validator's usage pattern.

**Comment by XiaoningLiu** [comment]
@3jr This issue has been fixed in https://github.com/Azure/azure-storage-node/pull/416
