### ISSUE TITLE
RangeError: Array buffer allocation failed

### ISSUE THREAD

**Issue by MarioPerezEsteso** [Azure/azure-storage-node#464]
We are using the version 1.4.0 of this library and we are receiving this error when we try to make 500 connections in batches of 10 to Azure Storage:

```
Array buffer allocation failed\nStack: RangeError: Array buffer allocation failed
at Buffer.Uint8Array (native)
at FastBuffer (buffer.js:11:5)
at createUnsafeBuffer (buffer.js:38:12)
at allocate (buffer.js:181:12)
at Function.Buffer.allocUnsafe (buffer.js:141:10)
at new Buffer (buffer.js:78:19)
at ChunkStream._allocateNewBuffer (D:\\home\\site\\wwwroot\\jobs\\job-utils\\node_modules\\azure-storage\\lib\\common\\streams\\chunkstream.js:262:18)
at ChunkStream._copyToInternalBuffer (D:\\home\\site\\wwwroot\\jobs\\job-utils\\node_modules\\azure-storage\\lib\\common\\streams\\chunkstream.js:214:25)
at ChunkStream._buildChunk (D:\\home\\site\\wwwroot\\jobs\\job-utils\\node_modules\\azure-storage\\lib\\common\\streams\\chunkstream.js:149:12)
at ChunkStream.write (D:\\home\\site\\wwwroot\\jobs\\job-utils\\node_modules\\azure-storage\\lib\\common\\streams\\chunkstream.js:129:8)
at Request.ondata (stream.js:31:26)
at emitOne (events.js:101:20)
at Request.emit (events.js:188:7)
at IncomingMessage.<anonymous> (D:\\home\\site\\wwwroot\\jobs\\job-utils\\node_modules\\request\\request.js:962:12)
at emitOne (events.js:96:13)
at IncomingMessage.emit (events.js:188:7)
```

Do you have any clue on what could be happening?

**Comment by XiaoningLiu** [comment]
Array buffer allocation failed usually happens due to memory exhausted. Please check your Node.js 32 or 64, switch to 64 will allow a larger memory.

**Comment by MarioPerezEsteso** [comment]
We are already using 64 bits.
