### ISSUE TITLE
403 forbidden error when createShareIfNotExists

### ISSUE THREAD

**Issue by yungezz** [Azure/azure-storage-node#490]
I have a vscode extension, which call createShareIfNotExists to createFileShare. While I found that on one of my laptop, this call always got 403 error, but this scenario is not reproachable on other machines.

I debugged the code, its' using correct account name and key(reason why it passed on other machine). I did some search found, storage auth might fail with 403 if time between service and request time stamp is out of sync. And I did see some time service error on that laptop. 
```
The time provider 'VMICTimeProvider' has indicated that the current hardware and operating environment is not supported and has stopped. This behavior is expected for VMICTimeProvider on non-HyperV-guest environments. This may be the expected behavior for the current provider in the current operating environment as well.
```

actually my laptop date & time setting is in right time zone, right time. No idea why this 403 happens even with right accoutn name and key. below is sample call and response
```
activating extension
Starting express server on port: 1863
[2018-07-26T06:41:20.624Z]debug : FINAL REQUEST OPTIONS:
{ uri: 'https://csxxxxxxx.file.core.windows.net:443/xxxxxxxxxxxxxx?restype=share',
  method: 'HEAD',
  headers: 
   { 'x-ms-client-request-id': 'e7fd9bb0-909e-11e8-871f-919af9f38dfd',
     'user-agent': 'Azure-Storage/2.10.0 (NODE-VERSION v7.9.0; Windows_NT 10.0.16299)',
     'x-ms-version': '2018-03-28',
     'x-ms-date': 'Thu, 26 Jul 2018 06:41:20 GMT',
     accept: 'application/atom+xml,application/xml',
     'Accept-Charset': 'UTF-8',
     'content-type': '',
     'content-length': 0,
     authorization: 'SharedKey csxxxxx:xxxxx' },
  mode: 'disable-fetch',
  encoding: undefined,
  timeout: 120000,
  forever: true }
[2018-07-26T06:41:21.230Z]debug : RESPONSE:
{ error: 
   { Error: 
     at Function.StorageServiceClient._normalizeError (C:\work\vscode-ansible\node_modules\azure-storage\lib\common\services\storageserviceclient.js:1198:23)
     at FileService.StorageServiceClient._processResponse (C:\work\vscode-ansible\node_modules\azure-storage\lib\common\services\storageserviceclient.js:744:50)
     at Request.processResponseCallback [as _callback] (C:\work\vscode-ansible\node_modules\azure-storage\lib\common\services\storageserviceclient.js:317:37)
     at Request.init.self.callback (C:\work\vscode-ansible\node_modules\request\request.js:185:22)
     at emitTwo (events.js:106:13)
     at Request.emit (events.js:194:7)
     at Request.<anonymous> (C:\work\vscode-ansible\node_modules\request\request.js:1157:10)
     at emitOne (events.js:96:13)
     at Request.emit (events.js:191:7)
     at IncomingMessage.<anonymous> (C:\work\vscode-ansible\node_modules\request\request.js:1079:12)
     at Object.onceWrapper (events.js:293:19)
     at emitNone (events.js:91:20)
     at IncomingMessage.emit (events.js:188:7)
     at endReadableNT (_stream_readable.js:975:12)
     at _combinedTickCallback (internal/process/next_tick.js:80:11)
     at process._tickCallback (internal/process/next_tick.js:104:9)
     name: 'StorageError',
     message: 'Forbidden',
     code: 'Forbidden',
     statusCode: 403,
     requestId: 'd8c8e114-201a-0073-4cab-24def7000000' },
  response: 
   { isSuccessful: false,
     statusCode: 403,
     body: '',
     headers: 
      { 'transfer-encoding': 'chunked',
        server: 'Microsoft-HTTPAPI/2.0',
        'x-ms-request-id': 'd8c8e114-201a-0073-4cab-24def7000000',
        'x-ms-error-code': 'AuthenticationFailed',
        date: 'Thu, 26 Jul 2018 06:41:20 GMT' },
     md5: undefined } }

```

**Comment by XiaoningLiu** [comment]
There is a header x-ms-request-source-ikey received in Storage server side, but not in your attached request headers log. Can you check why this header is there?

Following are server side log for this request. Removed header value of x-ms-request-source-ikey

info: NephosFile.exe: Info: Processing exception: Microsoft.Cis.Services.Nephos.Common.Authentication.AuthenticationFailureException : The MAC signature found in the HTTP request 'GEiI8aunitHfD+m13DS92yrv7/gnXTaoNaVuiVJIRGU=' is not the same as any computed signature. Server used following string to sign: 'HEAD............x-ms-client-request-id:e7fd9bb0-909e-11e8-871f-919af9f38dfd.x-ms-date:Thu, 26 Jul 2018 06:41:20 GMT.x-ms-request-source-ikey:[removed value in this GitHub Issue].x-ms-version:2018-03-28./cs1685ba005af8dx4b04x8f1/cs-yungez-microsoft-com-10030000801c0bf6.restype:share'.

**Comment by yungezz** [comment]
no idea of why the header was there. here's my code to make storage call,

https://github.com/VSChina/vscode-ansible/blob/f832e5d6e1d87982506ea7159dbe1320233d507e/src/azureStorageHelper.ts#L10

https://github.com/VSChina/vscode-ansible/blob/f832e5d6e1d87982506ea7159dbe1320233d507e/src/azureStorageHelper.ts#L24

azure storage version:
```
"azure-storage": "^2.8.2",
```

**Comment by XiaoningLiu** [comment]
@yungezz A similar issue https://github.com/Microsoft/ApplicationInsights-node.js/issues/143

**Comment by yungezz** [comment]
thanks for investigation. Just curious, why the issue only reproducible on some machines, on majority cases, it works well.

**Comment by XiaoningLiu** [comment]
@yungezz  sorry for the late response. It's hard to say without investigation, there maybe some plugins or other environments difference.

**Comment by yungezz** [comment]
@XiaoningLiu  thanks for investigation. We've got more and more customer escalation on this issue. Our extension code didn't specify the header `x-ms-request-source-ikey`, but directly call sdk methods. Is there way to find out where the header was added? meanwhile, is there way to workaround this issue? Thanks.

**Comment by yungezz** [comment]
@XiaoningLiu  any update on this?

**Comment by XiaoningLiu** [comment]
@yungezz azure-storage-node doesn't set the header. I cannot tell which VSC plugin or extension modify the request before sending out. You need some debugging to find out who modify this.

Using shared key for authentication will force Azure Storage server check headers integrity, e.g. injecting headers will lead auth error.

But one workaround is that you can use Azure Storage SAS token or OAuth token for authentication.

**Comment by yungezz** [comment]
@XiaoningLiu I did debug the extension, the extension has no way to add header to request to azure storage since we're calling sdk to make the call, you can see it from code  snippet:
```
const client = storage.createFileService(storageAccountName, storageAccountKey);

...
function createFileShare(client: FileService, fileShareName: string): Promise<void> {
    return new Promise<void>((resolve, reject) => {
        client.createShareIfNotExists(fileShareName, (err, result, response) => {
            if (err) {
                reject(err);
            } else {
                resolve();
            }
        });
    })
}
```

we'll try using SAS token to see if the error persistents.

**Comment by yungezz** [comment]
i tried sas token, met same error:
```

[2018-09-10T13:07:07.921Z]debug : FINAL REQUEST OPTIONS:
{ uri: 'https://cs1685ba005af8dx4b04x8f1.file.core.windows.net:443/xxxxxx?restype=share&se=9999-10-01T00%3A00%3A00Z&sp=rw&sv=2017-07-29&sr=s&sig=qqqqqqqqqqqqqqqqrh6AhEDxDihNigV%2F9zRE%3D&api-version=2017-07-29',
  method: 'HEAD',
  headers: 
   { 'x-ms-client-request-id': '6bdab880-b4fa-11e8-a3fa-4929c2f2bc28',
     'user-agent': 'Azure-Storage/2.8.2 (NODE-VERSION v7.9.0; Windows_NT 10.0.16299)',
     'x-ms-version': '2017-07-29',
     'x-ms-date': 'Mon, 10 Sep 2018 13:07:07 GMT',
     accept: 'application/atom+xml,application/xml',
     'Accept-Charset': 'UTF-8',
     'content-type': '',
     'content-length': 0 },
  mode: 'disable-fetch',
  encoding: undefined,
  timeout: 120000,
  forever: true }
[2018-09-10T13:07:13.144Z]debug : RESPONSE:
{ error: 
   { Error: 
   	at Function.StorageServiceClient._normalizeError (C:\work\vscode-ansible\node_modules\azure-storage\lib\common\services\storageserviceclient.js:1191:23)
   	at FileService.StorageServiceClient._processResponse (C:\work\vscode-ansible\node_modules\azure-storage\lib\common\services\storageserviceclient.js:738:50)
   	at Request.processResponseCallback [as _callback] (C:\work\vscode-ansible\node_modules\azure-storage\lib\common\services\storageserviceclient.js:311:37)
   	at Request.init.self.callback (C:\work\vscode-ansible\node_modules\azure-storage\node_modules\request\request.js:186:22)
   	at emitTwo (events.js:106:13)
   	at Request.emit (events.js:194:7)
   	at Request.<anonymous> (C:\work\vscode-ansible\node_modules\azure-storage\node_modules\request\request.js:1163:10)
   	at emitOne (events.js:96:13)
   	at Request.emit (events.js:191:7)
   	at IncomingMessage.<anonymous> (C:\work\vscode-ansible\node_modules\azure-storage\node_modules\request\request.js:1085:12)
   	at Object.onceWrapper (events.js:293:19)
   	at emitNone (events.js:91:20)
   	at IncomingMessage.emit (events.js:188:7)
   	at endReadableNT (_stream_readable.js:975:12)
   	at _combinedTickCallback (internal/process/next_tick.js:80:11)
   	at process._tickCallback (internal/process/next_tick.js:104:9)
     name: 'StorageError',
     message: 'Forbidden',
     code: 'Forbidden',
     statusCode: 403,
     requestId: 'ca542441-d01a-00e2-6407-49dae4000000' },
  response: 
   { isSuccessful: false,
     statusCode: 403,
     body: '',
     headers: 
      { 'transfer-encoding': 'chunked',
        server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
        'x-ms-request-id': 'ca542441-d01a-00e2-6407-49dae4000000',
        'x-ms-version': '2017-07-29',
        'x-ms-error-code': 'AuthorizationFailure',
        date: 'Mon, 10 Sep 2018 13:07:12 GMT' },
     md5: undefined } }

```

**Comment by yungezz** [comment]
Hi @XiaoningLiu  how to create an issue for storage service?  I suspect the issue in service side, because use same sas token on different machines got different results.

**Comment by yungezz** [comment]
close this since sas workaround the issue.
