### ISSUE TITLE
TypeError when connection string has no DefaultEndpointsProtocol

### ISSUE THREAD

**Issue by princjef** [Azure/azure-storage-node#548]
### Which service(blob, file, queue, table) does this issue concern?

All (encountered with blob)

### Which version of the SDK was used?

2.10.2

### What's the Node.js/Browser version?

Node.js 8.14.0

### What problem was encountered?

When providing a connection string with no `DefaultEndpointsProtocol`, calls with the client fail with a `TypeError` indicating that it cannot read `'primaryHost'` from an undefined object.

### Steps to reproduce the issue?

```ts
import * as storage from 'azure-storage';

const service = storage.createBlobService('AccountName=<your-account>;AccountKey=<your-key>;EndpointSuffix=core.windows.net');
service.doesContainerExist('test', (err, result) => {
    // err -> TypeError
});
```

This example causes the following TypeError to be thrown:

```
TypeError: Cannot read property 'primaryHost' of undefined
    at BlobService.StorageServiceClient._invalidLocationMode (/mnt/c/Users/jepri/dev/saas/service-continuous-data-export/node_modules/azure-storage/lib/common/services/storageserviceclient.js:1337:45)
    at BlobService.StorageServiceClient._validateLocation (/mnt/c/Users/jepri/dev/saas/service-continuous-data-export/node_modules/azure-storage/lib/common/services/storageserviceclient.js:1303:11)
    at operation (/mnt/c/Users/jepri/dev/saas/service-continuous-data-export/node_modules/azure-storage/lib/common/services/storageserviceclient.js:298:10)
    at /mnt/c/Users/jepri/dev/saas/service-continuous-data-export/node_modules/azure-storage/lib/common/services/storageserviceclient.js:561:9
    at BlobService.filter (/mnt/c/Users/jepri/dev/saas/service-continuous-data-export/node_modules/azure-storage/lib/common/services/storageserviceclient.js:1012:7)
    at BlobService.StorageServiceClient._performRequest (/mnt/c/Users/jepri/dev/saas/service-continuous-data-export/node_modules/azure-storage/lib/common/services/storageserviceclient.js:544:8)
    at BlobService.StorageServiceClient.performRequest (/mnt/c/Users/jepri/dev/saas/service-continuous-data-export/node_modules/azure-storage/lib/common/services/storageserviceclient.js:201:10)
    at BlobService._doesContainerExist (/mnt/c/Users/jepri/dev/saas/service-continuous-data-export/node_modules/azure-storage/lib/services/blob/blobservice.core.js:5307:8)
    at BlobService.doesContainerExist (/mnt/c/Users/jepri/dev/saas/service-continuous-data-export/node_modules/azure-storage/lib/services/blob/blobservice.core.js:510:8)
```

### Have you found a mitigation/solution?

Including the `DefaultEndpointsProtocol` resolves the error, but for this case I would expect it to either work by falling back to some built-in default value or throw a specific error that indicates that the connection string is invalid.

Without a fix, clients that are dynamically provided a connection string are left either catching all `TypeError`s (not ideal) or trying to check specific error messages to see if this specific bug is encountered.

It looks like the error stems from this logic, which doesn't set up the host if the scheme is missing:

https://github.com/Azure/azure-storage-node/blob/66d24e89ee/lib/common/services/storageservicesettings.js#L364-L379

**Comment by XiaoningLiu** [comment]
Hi @princjef  Thanks for reporting and your detailed investigation.

`DefaultEndpointsProtocol` is a required connection string segment. And the connection string error handling should be improved.

For your reference, for the next generation Storage V10 SDKs, they will not accept a connection string anymore.

**Comment by princjef** [comment]
Thanks for the quick response @XiaoningLiu!

It's good to know that the `DefaultEndpointsProtocol` is required. In that case, would it make sense to remove [this option](https://github.com/Azure/azure-storage-node/blob/66d24e89ee/lib/common/services/storageservicesettings.js#L230-L243), which allows it through without `DefaultEndpointsProtocol`? It appears to be the same as the check before it, but without requiring that key.

> For your reference, for the next generation Storage V10 SDKs, they will not accept a connection string anymore.

Thanks for the heads up! Will the expectation become that all values (account name, key, etc.) are provided individually?

**Comment by XiaoningLiu** [comment]
@princjef  For V10, yes. Here is a sample https://github.com/Azure/azure-storage-js/blob/master/blob/samples/basic.sample.js#L19
