### ISSUE TITLE
ESOCKETTIMEDOUT when trying to read small/medium sized blob to stream

### ISSUE THREAD

**Issue by joeyl426** [Azure/azure-storage-node#579]
### Which service(blob, file, queue, table) does this issue concern?
Blob 

### Which version of the SDK was used?
2.10.2

### What's the Node.js/Browser version?
v8.12.0

### What problem was encountered?
Every few calls to Read a blob (~18 MB) to a stream will hang for two minutes and result in the following error, the calls that succeed only take 1.5-2 seconds:

We are running a service on an Azure Linux VM and the issue seems to worsen when the server is getting requests in quick succession.

2019-04-17T17:10:17.498739135Z internal/streams/legacy.js:59
2019-04-17T17:10:17.498777236Z       throw er; // Unhandled stream error in pipe.
2019-04-17T17:10:17.498849039Z       ^
2019-04-17T17:10:17.498857239Z
2019-04-17T17:10:17.498864739Z Error: ESOCKETTIMEDOUT
2019-04-17T17:10:17.498872940Z     at ClientRequest.<anonymous> (/home/site/wwwroot/node_modules/request/request.js:816:19)
2019-04-17T17:10:17.498881340Z     at Object.onceWrapper (events.js:313:30)
2019-04-17T17:10:17.498889240Z     at emitNone (events.js:106:13)
2019-04-17T17:10:17.498896940Z     at ClientRequest.emit (events.js:208:7)
2019-04-17T17:10:17.498904741Z     at TLSSocket.emitTimeout (_http_client.js:708:34)
2019-04-17T17:10:17.498912241Z     at Object.onceWrapper (events.js:313:30)
2019-04-17T17:10:17.498920041Z     at emitNone (events.js:106:13)
2019-04-17T17:10:17.498927641Z     at TLSSocket.emit (events.js:208:7)
2019-04-17T17:10:17.498946042Z     at TLSSocket.Socket._onTimeout (net.js:407:8)
2019-04-17T17:10:17.498954342Z     at ontimeout (timers.js:475:11)
2019-04-17T17:10:17.536627481Z npm ERR! code ELIFECYCLE
2019-04-17T17:10:17.537805920Z npm ERR! errno 1
2019-04-17T17:10:17.543795217Z npm ERR! extensionsloader@0.0.0 start: `node ./bin/www`
2019-04-17T17:10:17.544459939Z npm ERR! Exit status 1
2019-04-17T17:10:17.545185563Z npm ERR!
2019-04-17T17:10:17.545761382Z npm ERR! Failed at the extensionsloader@0.0.0 start script.
2019-04-17T17:10:17.546307600Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-04-17T17:10:17.573533195Z
2019-04-17T17:10:17.574806837Z npm ERR! A complete log of this run can be found in:
2019-04-17T17:10:17.575692166Z npm ERR!     /root/.npm/_logs/2019-04-17T17_10_17_553Z-debug.log

### Steps to reproduce the issue?
The following code snippet produces the issue: 
```
var readStream = blobSvc.createReadStream(req.query.id, blobs[0].name, (error) => {
          if(error){
            console.log(error);
            res.end();
          }
      })
```

### Have you found a mitigation/solution?
No

**Comment by jiacfan** [comment]
Hi, joeyl426 

Thanks for reaching us. Can this issue get steady repro? And would you provide the requestId for recent problematic calls?

At same time, what's the write target for the read stream, are you downloading data to Linux VM, or piping to other destination?

Best Regards,
Jiachen

**Comment by vinjiang** [comment]
Please don't hesitate to let us know if any further assistance we can provide.

**Comment by joeyl426** [comment]
Turned out this was a client side issue!

**Comment by XiaoningLiu** [comment]
@jiacfan 

> Turned out this was a client side issue!

**Comment by jiacfan** [comment]
@joeyl426 

Would you share more details about it? What kind of client side issue it is?

Thanks,
Jiachen

**Comment by joeyl426** [comment]
I had an object in a client-side C++ class which was making a network request to a NodeJS service which would stream the blob back to the client. The pointer to this network request object was being reassigned partway through the request which interrupted the network request. This scenario caused the above error.
