### ISSUE TITLE
AzureBlobTraceListener ThreadAbortException

### ISSUE THREAD

**Issue by schmidtaa** [Azure/azure-storage-node#580]
### Which service(blob, file, queue, table) does this issue concern?

blob

### Which version of the SDK was used?

4.7.3324.0 built by: NET472REL1LAST_C

### What's the Node.js/Browser version?

N/A

### What problem was encountered?

2019-04-19T22:53:39
Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
   at Microsoft.WindowsAzure.WebSites.Diagnostics.AzureBlobTraceListener.AppendStreamToBlob(Stream stream)
   at Microsoft.WindowsAzure.WebSites.Diagnostics.AzureBlobTraceListener.ConsumeBuffer()
Request Information
RequestID:a912f750-c01e-011a-3302-f7a557000000
RequestDate:Fri, 19 Apr 2019 22:53:38 GMT
StatusMessage:The specified block list is invalid.
ErrorCode:InvalidBlockList

2019-04-19T22:43:49
System.Threading.ThreadAbortException: Thread was being aborted.
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
   at Microsoft.WindowsAzure.WebSites.Diagnostics.AzureBlobTraceListener.AppendStreamToBlob(Stream stream)
   at Microsoft.WindowsAzure.WebSites.Diagnostics.AzureBlobTraceListener.ConsumeBuffer()

2019-04-19T22:43:49
System.Threading.ThreadAbortException: Thread was being aborted.
   at Microsoft.WindowsAzure.WebSites.Diagnostics.AzureBlobTraceListener.ConsumeBuffer()
   at Microsoft.WindowsAzure.WebSites.Diagnostics.BaseTraceListener.FlushBuffer(Boolean waitForCompletion)

2019-04-19T22:43:49
System.Threading.ThreadAbortException: Thread was being aborted.
   at Microsoft.WindowsAzure.WebSites.Diagnostics.BaseTraceListener.FlushBuffer(Boolean waitForCompletion)
   at Microsoft.WindowsAzure.WebSites.Diagnostics.BaseTraceListener.OnFlushBuffer(Object state)

### Have you found a mitigation/solution?

No

**Comment by XiaoningLiu** [comment]
Please open issue to Azure Storage .Net SDK repo http://github.com/azure/azure-storage-net

**Comment by schmidtaa** [comment]
Opened in azure-storage-net
