### ISSUE TITLE
ESOCKETTIMEDOUT error

### ISSUE THREAD

**Issue by SparkSnail** [Azure/azure-storage-node#604]
### Which service(blob, file, queue, table) does this issue concern? 
file

### Which version of the SDK was used? 
v2.10.2

### What's the Node.js/Browser version? 
node v1.10.3

### What problem was encountered?
When I call `client.createFileFromLocalFile()` or `client.createDirectoryIfNotExists()` function, I will meet the error below:

{ Error: ESOCKETTIMEDOUT
      at ClientRequest.<anonymous> (/home/nni/.local/nni/node_modules/request/request.js:816:19)
      at Object.onceWrapper (events.js:273:13)
      at ClientRequest.emit (events.js:182:13)
      at TLSSocket.emitRequestTimeout (_http_client.js:661:40)
      at Object.onceWrapper (events.js:273:13)
      at TLSSocket.emit (events.js:182:13)
      at TLSSocket.Socket._onTimeout (net.js:449:8)
      at ontimeout (timers.js:436:11)
      at tryOnTimeout (timers.js:300:5)
      at listOnTimeout (timers.js:263:5) code: 'ESOCKETTIMEDOUT', connect: false } 

This error is shown random, but if I call the client frequently, this error will happen  definitely.

### Steps to reproduce the issue?
call  `createFileFromLocalFile` or `createDirectoryIfNotExists` function frequently.

### Have you found a mitigation/solution?
no

**Comment by XiaoningLiu** [comment]
Hi @SparkSnail ESOCKETTIMEDOUT is network error. Please enable retry policy to help with final success.

```javascript
var azure = require('azure-storage');
var retryOperations = new azure.ExponentialRetryPolicyFilter();
var blobService = azure.createBlobService().withFilter(retryOperations)
```

http://azure.github.io/azure-storage-node/ExponentialRetryPolicyFilter.html
