### ISSUE TITLE
ReferenceError: err is not defined

### ISSUE THREAD

**Issue by samyonr** [Azure/azure-storage-node#63]
azure-storage/lib/services/blob/blobservice.js:3607:7

what I did is tried to use createBlockBlobFromLocalFile with file with very (very) long name (hoped to catch and error, but it crashed).

full log:
ReferenceError: err is not defined
    at /var/www/html/ex2/server.js:279:94
    at finalCallback (/var/www/html/ex2/node_modules/azure-storage/lib/services/blob/blobservice.js:3607:7)
    at /var/www/html/ex2/node_modules/azure-storage/lib/common/filters/retrypolicyfilter.js:174:13
    at /var/www/html/ex2/node_modules/azure-storage/lib/common/services/storageserviceclient.js:651:17
    at /var/www/html/ex2/node_modules/azure-storage/lib/common/services/storageserviceclient.js:818:11
    at /var/www/html/ex2/node_modules/azure-storage/lib/common/services/storageserviceclient.js:650:15
    at processResponseCallback (/var/www/html/ex2/node_modules/azure-storage/lib/services/blob/blobservice.js:3610:5)
    at Request.processResponseCallback [as _callback] (/var/www/html/ex2/node_modules/azure-storage/lib/common/services/storageserviceclient.js:287:13)
    at Request.self.callback (/var/www/html/ex2/node_modules/azure-storage/node_modules/request/request.js:129:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/var/www/html/ex2/node_modules/azure-storage/node_modules/request/request.js:873:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/var/www/html/ex2/node_modules/azure-storage/node_modules/request/request.js:824:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)

**Comment by samyonr** [comment]
solved - not azure-storage-node problem. sorry
