### ISSUE TITLE
Difference btw Rest api to download image vs blokblobClient.download() and ERRCONREST and ERTIMOUT

### ISSUE THREAD

**Issue by DVGY** [Azure/azure-storage-node#669]
I am trying to download 1246 images and as of now I am using this code

```
 downloadImage: async function (AzureStoreURL, filename, requestID, context) {
    try {
      return new Promise((resolve, reject) => {
        fetch(AzureStoreURL + encodeURI(filename))
          .then((res) => {
            if (!fs.existsSync(path.join(__dirname, "..", requestID))) {
              fs.mkdirSync(path.join(__dirname, "..", requestID));
            }

            const fileStream = fs.createWriteStream(
              path.join(__dirname, "..", requestID, `${filename}`)
            );

            res.body.pipe(fileStream);
            fileStream.on("finish", function () {
              fileStream.close();
              resolve(`${filename}`);
            });

            fileStream.on("error", function (e) {
              reject(e);
            });
          })
          .catch((err) => {
            context.log("I am rejected and in catch block");
            context.log(err);
            reject(err);
          });
      });
    } catch (e) {
      reject(e);
      context.info({ e });
    }
  },
```

```
const limit = pLimit(200);
const allDownloadPromises = imageItems.map((item) => {
   
                  return limit(() =>
                    downloadImage(
                      config.AzureStoreURL,
                      item,
                      requestID,
                      context
                    )
                  );
      });

await Promise.allSettled(allDownloadPromises);
```
I am getting this error
```
FetchError: request to https://{mystorageurl}/{mycontainer}/%E8%B0%83%E6%95%B4%E5%A4%A7%E5%B0%8F%20IMG_20201116_143840-5c79a95d-b4a3-459a-906c-68216f5b5bcb.jpg failed,
reason: read ECONNRESET at ClientRequest.<anonymous> (/home/site/wwwroot/node_modules/node-fetch/lib/index.js:1461:11) at ClientRequest.emit (events.js:314:20) at TLSSocket.socketErrorListener (_http_client.js:427:9) at TLSSocket.emit (events.js:314:20) at
 emitErrorNT (internal/streams/destroy.js:92:8) at emitErrorAndCloseNT (internal/streams/destroy.js:60:3) 

at processTicksAndRejections (internal/process/task_queues.js:84:21) { type: 'system', errno: 'ECONNRESET', code: 'ECONNRESET' }
```

```
FetchError: request to https://{mystorageurl}/{mycontainer}/IMG_20201118_025746_%E8%B0%83%E6%95%B4%E5%A4%A7%E5%B0%8F-b700f135-c716-4e1d-b88f-e16c4535688c.jpg failed,
 reason: connect ETIMEDOUT 13.88.144.240:443 at ClientRequest.<anonymous> (/home/site/wwwroot/node_modules/node-fetch/lib/index.js:1461:11) at ClientRequest.emit (events.js:314:20) at TLSSocket.socketErrorListener (_http_client.js:427:9) at TLSSocket.emit (events.js:314:20) at
 emitErrorNT (internal/streams/destroy.js:92:8) at emitErrorAndCloseNT (internal/streams/destroy.js:60:3) at 


processTicksAndRejections (internal/process/task_queues.js:84:21) { type: 'system', errno: 'ETIMEDOUT', code: 'ETIMEDOUT' }
```

Is there any difference btw using `rest api to download image vs blokblobClient.download()` like rest api used http 1.1 and blockblobClient uses http 2 ? 

How can I diagnose this issue ?

About a month ago i ran this code and it was working like a charm, but now it's erroring out I don't know why.

**Comment by EmmaZhu** [comment]
Hi @DVGY ,

Could you have a try with latest storage package @storage/storage-blob?  If you see any problem with it, please open an issue in [](https://github.com/Azure/azure-sdk-for-js).

Thanks
Emma

**Comment by EmmaZhu** [comment]
Hi @DVGY , 

Does this issue still happen? 
From the error message, the issue may be caused by a transient network issue. 

`blokblobClient.download()` in the SDK also uses REST API. You can treat it as a more convenience function to use REST API.

Thanks
Emma
