### ISSUE TITLE
 Can't resolve 'fs' in 'C:\temp\nextblogs\node_modules\azure-storage\lib\services\blob'

### ISSUE THREAD

**Issue by chenxizhang** [Azure/azure-storage-node#671]
> For latest features support, please switch to [Azure Storage JavaScript SDK V10](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage). 

### Which service(blob, file, queue, table) does this issue concern?
table

### Which version of the SDK was used?
2.10.3

### What's the Node.js/Browser version?
14.4

### What problem was encountered?
ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in 'C:\temp\nextblogs\node_modules\azure-storage\lib\services\blob'

### Steps to reproduce the issue?
npm install azure-storage
npm run build

### Have you found a mitigation/solution?
No

**Comment by chenxizhang** [comment]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v14.4.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle nextblogs@0.1.0~prebuild: nextblogs@0.1.0
6 info lifecycle nextblogs@0.1.0~build: nextblogs@0.1.0
7 verbose lifecycle nextblogs@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle nextblogs@0.1.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\temp\nextblogs\node_modules\.bin;C:\Program Files\PowerShell\7;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Program Files\Common Files\Microsoft Shared\Microsoft Online Services;C:\Program Files (x86)\Common Files\Microsoft Shared\Microsoft Online Services;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files (x86)\dotnet\;C:\Program Files\PowerShell\7\;C:\Users\arechen\AppData\Local\Microsoft\WindowsApps;;C:\Users\arechen\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\arechen\AppData\Roaming\npm;C:\Users\arechen\.dotnet\tools
9 verbose lifecycle nextblogs@0.1.0~build: CWD: C:\temp\nextblogs
10 silly lifecycle nextblogs@0.1.0~build: Args: [ '/d /s /c', 'next build' ]
11 silly lifecycle nextblogs@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle nextblogs@0.1.0~build: Failed to exec build script
13 verbose stack Error: nextblogs@0.1.0 build: `next build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1051:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid nextblogs@0.1.0
15 verbose cwd C:\temp\nextblogs
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v14.4.0
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error nextblogs@0.1.0 build: `next build`
22 error Exit status 1
23 error Failed at the nextblogs@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by chenxizhang** [comment]
it seems related to NextJS framework, it works in pure React page.
