### ISSUE TITLE
"blob show" command fails with "invalid usage of '_'" after underscore update

### ISSUE THREAD

**Issue by russelarms** [Azure/azure-storage-node#688]
> For latest features support, please switch to [Azure Storage JavaScript SDK V10](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage). 

### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
2.10.4

### What's the Node.js/Browser version?
12.21.0

### What problem was encountered?
```
 error streamlining /usr/local/lib/node_modules/azure-cli/node_modules/azure-storage/node_modules/underscore/underscore-node-f.cjs: invalid usage of '_'
    STACK:
    Error: invalid usage of '_'
    at _doIt (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/transform.js:577:12)
    at _propagate (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/transform.js:179:58)
    at _doIt (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/transform.js:603:12)
    at _propagate (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/transform.js:169:20)
    at _doIt (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/transform.js:560:14)
    at _propagate (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/transform.js:169:20)
    at _doIt (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/transform.js:523:17)
    at _propagate (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/transform.js:169:20)
    at _doIt (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/transform.js:486:12)
    at _propagate (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/transform.js:169:20)
```

### Steps to reproduce the issue?
`azure storage blob show` or `blob list`

### Have you found a mitigation/solution?
Not yet.

**Comment by EmmaZhu** [comment]
@russelarms 

Seems you encountered this issue when using azure-cli. From the stack, I didn't see stack from azure-storage package. The error is reported from azure-storage's dependency "underscore".

Would you upgrade to the latest azure-cli and try again. The latest azure-cli doesn't have dependency on azure-storage anymore. 

BTW, we are deprecating this package. If you'd need a JS SDK for storage operations, we'd suggest to leverage packages: @storage/storage-blob, @storage/storage-file-share, @storage/storage-file-datalake, @storage/storage-queue. 

Thanks
Emma
